import I18n from 'react-native-i18n';

I18n.fallbacks = true;
I18n.translations = {
  en: {
    hi: 'Hi',
    help:'Help',
    update: 'Update',
    about: 'About',
    settings: 'Settings',
    plugin: 'Plugin',
    login: 'Login',
    logout: 'Logout',
    ask_logout: 'Do you want to logout from ',
    gg: 'Google',
    fb: 'Facebook',
    wx: 'Weixin',
    wb: 'Weibo',
    ok: 'OK',
    cancel: 'Cancel',
    usb: 'USB',
    ble: 'Bluetooth LE',
    map: 'Map',
  },
  zh_CN: {
    hi: '你好',
    help: '帮助',
    update: '更新',
    about: '关于',
    settings: '设置',
    plugin: '插件',
    login: '登录',
    logout: '退出',
    ask_logout: '确认退出',
    gg: '谷歌',
    fb: '脸书',
    wx: '微信',
    wb: '微博',
    ok: '确定',
    cancel: '取消',
    usb: 'USB',
    ble: '蓝牙',
    map: '地图',
  },
}
