import I18n from 'react-native-i18n';

I18n.fallbacks = true;
I18n.translations = {
  en: {
    shareplus: 'Share+',
    hi: 'Hi',
    help:'Help',
    update: 'Update',
    about: 'About',
    settings: 'Settings',
    plugin: 'Plugin',
    feed: 'Feed',
    login: 'Login',
    logout: 'Logout',
    post: 'Post',
    ask_logout: 'Do you want to logout from ',
    apple: 'Apple',
    baidu: 'Baidu',
    gg: 'Google',
    fb: 'Facebook',
    wx: 'Weixin',
    wb: 'Weibo',
    ok: 'OK',
    cancel: 'Cancel',
    usb: 'USB',
    ble: 'Bluetooth LE',
    map: 'Map',
    //form
    ask: 'Ask',
    title: 'Title',
    type: 'Type',
    cat: 'Category',
    time: 'Time',
    address: 'Location',
    dest: 'Destination',
    phone: 'Phone',
    price: 'Price',
    ctime: 'Publish Time',
    content: 'Detail Information',
    reply: 'Reply',
    replies: 'Replies',
    my_reply: 'My Reply',
    bathroom: 'Bathroom',
    bedroom: 'Bedroom',
    sell: 'Sell a ',
    buy: 'Buy a ',
    rent0: 'Find a ',
    rent1: 'Rent a ',
    free: 'Free ',
    publish: 'Publish',
    //type
    house: 'House',
    car:   'Car',
    mail:  'Mail',
    human: 'Human',
    ticket:'Ticket',
    book:  'Book',
    tool:  'Tool',
    food:  'Food',
    help:  'Help',
    medkit:'Medical',
    game:  'Game',
    phone: 'Cell',
    pc:    'Laptop',
    school:'Study',
    music: 'Music',
  },
  zh_CN: {
    shareplus: '分享家',
    hi: '你好',
    help: '帮助',
    update: '更新',
    about: '关于',
    settings: '设置',
    plugin: '订阅',
    feed: '插件',
    login: '登录',
    logout: '退出',
    post: '发布',
    ask_logout: '确认退出',
    apple: '苹果',
    baidu: '百度',
    gg: '谷歌',
    fb: '脸书',
    wx: '微信',
    wb: '微博',
    ok: '确定',
    cancel: '取消',
    usb: 'USB',
    ble: '蓝牙',
    map: '地图',
    //form
    ask: '求',
    title: '标题',
    type: '类型',
    cat: '类别',
    time: '时间',
    address: '地址',
    dest: '目的地',
    phone: '电话',
    price: '价格',
    ctime: '发布时间',
    content: '详细内容',
    reply: '回复',
    replies: '回复',
    my_reply: '我的回复',
    bathroom: '浴室',
    bedroom: '卧室',
    sell: '卖',
    buy: '买',
    rent0: '求租',
    rent1: '出租',
    free: '免费',
    publish: '发布',
    //type
    house: '房',
    car:   '车',
    mail:  '邮件',
    human: '人力',
    ticket:'票',
    book:  '书',
    tool:  '工具',
    food:  '吃',
    help:  '帮助',
    medkit:'医疗',
    game:  '游戏',
    phone: '手机',
    pc:    '电脑',
    school:'学习',
    music: '音乐',
  },
}
